---
language: bash

dist: trusty

env:
  - VERSION=9.2-jre7
  - VERSION=9.2-jre8
  - VERSION=9.3-jre8
  - VERSION=9.3-jre8 VARIANT=alpine
  - VERSION=9.4-jre8
  - VERSION=9.4-jre8 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "${VERSION}${VARIANT:+/$VARIANT}"
  - image="jetty:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build --pull -t "$image" .
  - ~/official-images/test/run.sh "$image"
